name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check HTML
      uses: chabad360/html5validator@master
    
    - name: Check JavaScript
      run: |
        npm install -g eslint
        eslint "**/*.js"
    
    - name: Build and Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: . # デプロイするディレクトリ
        branch: gh-pages # デプロイ先のブランチ 